include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_empty_else: true
    avoid_void_async: true
    avoid_print: true
    always_use_package_imports: true
    empty_catches: false
    unnecessary_new: true
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/generated_plugin_registrant.dart'
    - 'lib/l10n/l10n.dart'
    - "lib/core/dependency_injection/injection.config.dart"
    - "lib/bootstrap.dart"
    - 'test/**'
