name: spesochat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/
    # - .env.development
    # - .env.production

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
